project:
  type: website

website:
  title: "dummy test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: shiny.qmd
        text: Shiny

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
